export const CREATE_DIMENSION_TABLE_CARS =
  "CREATE TABLE IF NOT EXISTS DimCars (id SERIAL NOT NULL, plate VARCHAR(255), car_model VARCHAR(255) NOT NULL, car_brand VARCHAR(255) NOT NULL, year INT NOT NULL, color VARCHAR(255) NOT NULL, Created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(plate))";

export const CREATE_FACT_TABLE_CARS =
  "CREATE TABLE IF NOT EXISTS factCars (id SERIAL NOT NULL, slot_number INT NOT NULL, plate VARCHAR(255), start_date TIMESTAMPTZ DEFAULT NOW(), end_date TIMESTAMPTZ, Created_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(id), FOREIGN KEY(plate) REFERENCES DimCars(plate))";
